name: maizecare_frontend
description: Aplikasi monitoring kesehatan tanaman jagung
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  
  # State Management
  provider: ^6.1.1
  
  # Network & API
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Image
  image_picker: ^1.0.7
  
  # Charts
  fl_chart: ^0.66.0
  
  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/